---
abstract: 'API client for Stripe.com'
author:
  - 'Luke Closs'
  - 'Rusty Conover'
build_requires:
  DateTime: '0'
  DateTime::Duration: '0'
  Test::Exception: '0'
  Test::More: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Stripe
requires:
  HTTP::Request::Common: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  Moose: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::Clone: '0'
  MooseX::Method::Signatures: '0'
  Throwable: '0'
  URI::Escape: '0'
  namespace::clean: '0'
  overload: '0'
resources:
  bugtracker: https://github.com/lukec/stripe-perl/issues
  homepage: https://stripe.com/docs
  repository: git://github.com/lukec/stripe-perl.git
version: '0.13'
x_contributors:
  - 'Andrew Solomon <andrew@illywhacker.net>'
  - 'Brian Collins <bricollins@gmail.com>'
  - 'Devin M. Certas <devin@nacredata.com>'
  - 'Dimitar Petrov <mitakaa@gmail.com>'
  - 'Dylan Reinhold <dylan@gasdasoftware.com>'
  - 'Jonathan "Duke" Leto <jonathan@leto.net>'
  - 'Luke Closs <me@luk.ec>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Rusty Conover <rusty@luckydinosaur.com>'
  - 'Sachin Sebastian <sachinjsk@users.noreply.github.com>'
  - 'Tom Eliaz <tom@tomeliaz.com>'
