---
abstract: 'API client for Stripe.com'
author:
  - 'Luke Closs'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Stripe
no_index:
  directory:
    - inc
    - t
requires:
  HTTP::Request::Common: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Moose: 0
  Throwable: 0
  URI::Escape: 0
  methods: 0
  perl: "\x05\n\x01"
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
